[박민하]ProductListView 기능 추가
wecode-bootcamp-korea/34-2nd-Fake-Trip-backend pull request #21
Opened 2022-07-11 06:57 UTC by miracle-21

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [*] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 메인페이지, 검색결과페이지에서 필요한 데이터 추가

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 데이터 추가
- 위도, 경도
- 시설
- 평점
2. 금액 검색 조건 업데이트
- 1박당 금액에서 총 금액으로 수정
- 2박 3일, 20만원 이상의 숙소로 설정하면 1박에 10만원 이상의 숙소만 반환
4. 검색 기능 업데이트
- 지역이 '도'인 숙소를 검색하면, 지역에 '도'가 포함된 모든 숙소 반환
- 이름 '오름'인 숙소를 검색하면, 숙소 이름에 '오름'이 포함된 모든 숙소 반환

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 특정 문자가 포함된 문자열을 반환하는 방법을 알게 됨
- 총 금액을 기준으로 데이터를 반환할 수 있음

<br />

## :: 기타 질문 및 특이 사항
- 특이사항 : 코드테스트 에러, 수정 예정입니다.

2022-07-11 12:08 UTC, lordmyshepherd commented
start_date, end_date 기준으로 필터링 기능만 추가해주세요-!

```python
        # products?start_date=""&end_date=""&price=[0, 1000000]
        start_date = datetime.strptime(request.GET.get("start_date"), '%Y-%m-%d')
        end_date   = datetime.strptime(request.GET.get("end_date"), '%Y-%m-%d')
        sort       = request.GET.get('sort', 'id')
        offset     = int(request.GET.get('offset', 0))
        limit      = int(request.GET.get('limit', 100))

        FILTER_SET = {
            "name"   : "name__contains",
            "region" : "region__name__contains",
            "grade"  : "grade",
            "price"  : "room__price__range"
        }

        SORT_SET = {
            'random'             : '?',
            'check_in-ascending' : 'check_in',
            'price-asceding'     : 'low_price',
        }

        query    = { FILTER_SET[key] : json.loads(value) for key, value in request.GET.items()}
        products = Product.objects.filter(**query).order_by(SORT_SET[sort])[offset:offset+limit]

        results = [
            {
                'id'         : product.id,
                'name'       : product.name,
                'grade'      : product.grade,
                'address'    : product.address,
                'region'     : product.region.name,
                'check_in'   : product.check_in,
                'check_out'  : product.check_out,
                'latitude'   : product.latitude,
                'longtitude' : product.longtitude,
                'category'   : product.category.name,
                'main_image' : product.productimage_set.get(is_main=1).url,
                'amanity'    : [amanity.name for amanity in product.amenity.all()],
                'avg_rate'   : product.review_set.aggregate(avg = Avg('rating'))['avg'],
                'min_price'  : product.room_set.aggregate(min = Min('price',output_field=IntegerField()))['min'],
            } for product in products
        ]

        return JsonResponse({'results' : results}, status = 200)


```

2022-07-11 12:14 UTC, lordmyshepherd requested changes

2022-07-11 12:14 UTC, lordmyshepherd commented on products/views.py
> +        price = int(price) / len(search_date)
price는 일단 고려하지 않고 지워주세요.

2022-07-11 12:14 UTC, lordmyshepherd commented on products/views.py
> +                    'date' : len(search_date)
```suggestion
```

2022-07-11 12:14 UTC, lordmyshepherd commented on products/views.py
> +        search_date = pandas.date_range(start_date,end_date)[:-1]
```suggestion
```

2022-07-12 01:19 UTC, lordmyshepherd requested changes

2022-07-12 01:19 UTC, lordmyshepherd commented on users/views.py
> +    # @token_validator
왜 주석처리 하셨나요?

2022-07-12 02:38 UTC, miracle-21 commented on users/views.py
> +    # @token_validator
NameError: name 'token_validator' is not defined

에러 발생해서 주석처리 했습니다, 진관님이 지금 token_validator 추가중이어서 해당 pr merge 되면 다시 올리겠습니다.

2022-07-12 05:22 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-07-12 05:22 UTC, merged