[박민하]or 조건(검색 기능) 및 필터링 데이터 추가
wecode-bootcamp-korea/34-2nd-Fake-Trip-backend pull request #29
Opened 2022-07-12 08:37 UTC by miracle-21

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [x] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 검색 내용에 숙소 이름 또는 지역 이름이 포함된 경우 해당 데이터 반환
- 최소가, 최저가 호텔 가격 필터링
- 시설별 필터링

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 검색 기능에 or 조건 적용
- q객체 사용
- '서울'을 검색한다면 숙소 이름에 '서울'이 있거나, 지역 이름에 '서울'이 있는 모든 데이터 반환
2. 호텔 가격 필터링
- min_price, max_price를 받는 range 키워드 사용.
- 지정하지 않은 경우 최댓값과 최솟값은 0원, 100만원으로 지정
- 가격을 default와 min_price로 나눔
  - default는 호텔의 최저가로, 메인페이지에서 사용될 데이터
  - min_price는 필터링된 호텔 최저가로, 검색페이지에서 사용될 데이터 
3. 시설별 필터링
- q객체에서 amanity 추가 
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- range 키워드 사용

<br />

## :: 기타 질문 및 특이 사항
- test 코드 작성을 아직 못했습니다.
- 가격별 오름차순이 제대로 안되고 있는 중이라 수정이 필요합니다.

2022-07-12 09:08 UTC, lordmyshepherd requested changes

2022-07-12 09:08 UTC, lordmyshepherd commented on products/tests.py
> +>>>>>>> 8d58664... Update: add datas & searching method
컨플릭트 아직 해결 안된 부분이 있습니다! 지우고 다시 올려주세요-!

2022-07-12 09:16 UTC, miracle-21 commented on products/tests.py
> +>>>>>>> 8d58664... Update: add datas & searching method
넵 수정했습니다!

2022-07-13 01:24 UTC, lordmyshepherd commented
LGTM 👍🏻

2022-07-13 01:24 UTC, merged