[정진관] 예약 기능 구현
wecode-bootcamp-korea/34-2nd-Fake-Trip-backend pull request #32
Opened 2022-07-12 17:26 UTC by dingwan0331

Create : orders.Reservation.post

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ x ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 예약 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-07-13 04:34 UTC, lordmyshepherd requested changes

2022-07-13 04:34 UTC, lordmyshepherd commented on orders/views.py
> +            reservation_status_id = 1
`reservation_status_id = 1` 부분에서 1이 의미하는 값이 무엇인가요?

2022-07-13 05:40 UTC, dingwan0331 commented on orders/views.py
> +            reservation_status_id = 1
저희가 결제가 유저 포인트로 즉시 결제하다보니 결제 버튼을 누르는순간 
reservation_statuses 테이블의 id=1의 status는  '결제완료'
결제 대기의 개념이 없는 시스템이라 결제 누르는순간 '결제완료'가 되고 이외에 다른 status는 
'예약 완료' , '예약 취소중'   등등이 있습니다.
models.py 에서 default로 설정하려고 고민했는데 views에서 처리하는거랑 비슷한거 같아서 views.py 에서 처리했습니다.

2022-07-14 00:48 UTC, lordmyshepherd requested changes

2022-07-14 00:48 UTC, lordmyshepherd commented on orders/views.py
> +            reservation_status_id = 1
우선 이러한 상태값들은 Enum으로 관리하는 것이 좋습니다!
그 이유는 1을 하드코딩해서 사용하게되면 다른 누군가가 이 코드를 수정하거나 디버깅해야될 때, 의미를 파악하기가 어렵습니다!

참고)
```python
class ReservationStatus(Enum):
    DONE = 1
    CALNCEL = 2
    ..
```
```python
        Reservation.objects.create(
            room_id               = room_id,
            user_id               = request.user,
            start_date            = start_date,
            end_date              = end_date,
            guest_information     = guest_information,
            reservation_status_id = RservationStatus.DONE.value
```

2022-07-14 07:32 UTC, lordmyshepherd requested changes

2022-07-14 07:32 UTC, lordmyshepherd commented on core/validators.py
> +class Validators:
응용 👍🏻 

 참고)
지금도 모듈화 잘 하셨는데, 지금 구조는 검증 규칙이 변경되면 소스코드도 변경되게 구조가 만들어져 있습니다.
여기서 조금 더 나가본다면, 규칙 자체도 분리해서 외부에서 주입받는 방식으로 만들어본다면 확장성 있는 코드가 될 것 같네요~

```python
class UserValidationRule:
    def validate(self, user):
        return all(getattr(self, 'validate_' + key)(user) for key in self.__dict__.keys())

class UserNamevalidationRule(UserValidationRule):
    def __init__(self, max_length, min_length):
        self.max_length = max_length
        self.min_length = min_length

    def validate_min_length(self, user):
        return len(user["name"]) > self.min_length
    
    def validate_max_length(self, user):
        return len(user["name"]) < self.max_length
   
class PhoneNumberValidationRule(UserValidationRule):
    def __init__(self):
        self.phone_number_regex = ""

    def validate_phone_number_regex(self, user):
        return re.match(self.phone_number_regex, user.phone_number 
 
class UserValidation:
    def __init__(self, rules):
        self.rules = rules

    def validate(self, user):
        return all(rule.validate(user) for rule in self.rules)


# signup views.py
user  = {"name" : "홍홍홍", "phone_number" : "010-7402-0990"}
rules = [
    UserNamevalidationRule(max_length = 10, min_length = 5), 
    PasswordValidationRule(),
    BirthDateValidationRule(),
    PhoneNumberValidationRule()
]

validation = UserValidationRule(rules)
validation.validate(user)

# signin views.py
user  = {"name" : "홍홍홍", "password" : "xxxxxxx"}
rules = [
    UserNamevalidationRule(max_length = 10, min_length = 5), 
    PasswordValidationRule(),
]

validation = UserValidationRule(rules)
validation.validate(user)
```

2022-07-14 07:32 UTC, lordmyshepherd commented
LGTM 👍🏻

2022-07-14 07:32 UTC, merged