Create : users.views.SigninView
wecode-bootcamp-korea/34-2nd-Fake-Trip-backend pull request #5
Opened 2022-07-06 17:23 UTC by dingwan0331

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ x ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 카카오 소셜 로그인 기능 추가
<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 클라이언트에서 받은 토큰을 이용하여 카카오서버에서 유저의 정보를 얻었습니다.
2. 카카오서버에서 얻은 response의 body에 'code' 키가 있을시 에러 반환을 하였습니다.
3. get_or_create 를 사용하여 유저정보를 db에 저장 or 이미 있는 유저의 정보를 얻어왔습니다.
4. jwt를 사용하여 현재 서비스의 토큰을 클라이언트에게 전달하였습니다.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 백엔드에서 request를 보내는 법을 배웠습니다.
- 소셜로그인 API의 flow를 배울 수 있었습니다.

<br />

## :: 기타 질문 및 특이 사항
- 카카오에서 들어온 정보를 어느정도 까지 유효성 검사를 해야하는지 검사해야 하는지 궁금합니다.(중복검사, email 형식검사 등등)
- 저희 프로젝트에서는 카카오 로그인으로 인해 별도의 회원가입없이 진행됩니다.
- get_or_create 문을 통해 유저정보 저장 혹은 get을 하는데 이경우 Signup과 Signin 기능이 동시에 한 View에서 진행이되는데 View 컨벤션을 어떻게 해야할지 궁금합니다.

2022-07-07 01:48 UTC, lordmyshepherd requested changes

2022-07-07 01:48 UTC, lordmyshepherd commented on faketrip/settings.py
> +from my_settings import DATABASES, SECRET_KEY, ALGORYTHM
오타가 있네요! ALGORYTHM -> ALGORITHM

```suggestion
from my_settings import DATABASES, SECRET_KEY, ALGORYTHM
```

2022-07-07 01:48 UTC, lordmyshepherd commented on users/views.py
> +        access_token = json.loads(request.body).get('access_token')
access_token은 http request message의 bodt가 아니라 header의 `{"Authorization" : "xxxxxxxx"}` 형태로 값을 주고 받는 것이 좋겠습니다!

MDN 문서에서 HTTP headers > Autorization 자료를 참고해주시면 그 이유를 찾을 수 있을 것 같습니다.

2022-07-07 01:48 UTC, lordmyshepherd commented on users/views.py
> +        data         = requests.get(KAKAO_URL, headers={'Authorization': f'Bearer {access_token}'}).json()
requests 모듈을 사용하실 때에는 `timeout` 옵션을 반드시 설정해주셔야 합니다.
그 이유는 `timeout` 옵션을 추가하지 않으면 서버의 응답을 계속해서 기다리고 있는 문제가 발생 합니다.

2022-07-07 01:48 UTC, lordmyshepherd commented on users/views.py
> +            return JsonResponse({'message' : 'Kakao Server Error'}, status = 400)
> 카카오에서 들어온 정보를 어느정도 까지 유효성 검사를 해야하는지 궁금합니다.(중복검사, email 형식검사 등등)

앞에 질문 사항에 적어놓으신 내용과 같이 피드백을 드리자면, 

유효성 검사를 얼마나 엄격하게 하느냐는 회사마다, 개발자마다 다르기 때문에 정답은 없습니다.
다만 제 의견을 드리자면, 이 경우에는 사용자 정보를 제대로 받아오지 못한 경우를 전부 에러로 잡지 않을 것 같습니다!

그 이유는 아래와 같습니다.
1. 코드를 유지보수하는 측면에서, 자주 발생하지 않을 것 같은 에러 때문에 읽어야되는 코드가 늘어는 것.
2. -1, -9798 에러 핸들을 하지 않을 경우 버그가 발생할 수 있는가를 생각해 봤을 때, 그렇지 않다고 판단됨.
3. 2번에 연장선으로 모든 에러에 대해서 각각의 메세지를 정확하게 반환해줄 필요가 없음.

그래서, 저라면 status_code가 200이 아니라면 전부 Invalid token 메세지를 반환해줄 것 같습니다.

2022-07-07 01:48 UTC, lordmyshepherd commented on users/views.py
> +            email = email).id
아래와 같이 get_or_create()를 사용할 때, kakao에서 nickname이 변경되는 경우에 버그가 발생할 수 있을 것 같습니다.
진관님 생각은 어떠신가요?

2022-07-07 01:48 UTC, lordmyshepherd commented on users/views.py
> +class SigninView(View):
아래와 같이 `Kakao API` 관련된 로직은 class로 그룹핑할 수 있습니다.  

그렇게 되면 `Kakao API` 관련된 로직은 하나의 class에서 관리하면 된다는 장점이 있고, 만약에 나중에 `Kakao API` 호출부의 수정일 있을 경우 `KakaoLoginView`를 수정할 필요가 없이 `KakaoAPI` 클래스만 수정하면 됩니다. 

결국 `Kakao API`를 호출하는 위치에서는 Interface만 알고 사용하면 되고 내부적으로 어떻게 구현되었는지 알 필요가 없습니다.

힌트 예시)
```python
# kakao.py
class KakaoAPI:
    def __init__(self, access_token):
        self.access_token = access_token
        self.user_url     = "https://kapi.kakao.com/v2/user/me"
        self.map_url      = "https://..."

    def get_kakao_user_information(self):
        headers = {"Authorization": f"Bearer ${self.access_token}"}

        response = requests.get(self.user_url, headers=headers, timeout=3)
			  
        if not response.status_code == 200:
            return ...
	
        return response.json()

    def get_location():
        return ...
```

2022-07-07 01:49 UTC, lordmyshepherd commented
추가로 PR에는 기능 테스트 방법과 테스트 결과를 같이 적어주면 좋을 것 같습니다.

2022-07-07 01:50 UTC, lordmyshepherd commented on users/views.py
> +            email = email).id
> get_or_create 문을 통해 유저정보 저장 혹은 get을 하는데 이경우 Signup과 Signin 기능이 동시에 한 View에서 진행이되는데 View 컨벤션을 어떻게 해야할지 궁금합니다.

소셜로그인 자체가 회원가입과 로그인 기능을 동시에 하는 것이기 때문에, 잘 작성해 주셨습니다!
다만, 위에서 버그가 발생할 수 있는 부분만 수정되면 좋을 것 같습니다.

2022-07-07 03:49 UTC, dingwan0331 commented on users/views.py
> +            email = email).id
아하 수정해보겠습니다~

2022-07-07 12:58 UTC, dingwan0331 commented
1. social_apis.py 의 KakaoAPI 클래스를 작성하였습니다.
- status_code 가 200이 아닐시 예외처리 하였습니다. message = 'Invalid Token'
- requests.get()속성에 timeout을 추가하였습니다.

2. SinginView 수정
- get() 요청으로 수정하였습니다.
- 카카오 액세스 토큰, 프로젝트 액세스토큰을 클라이언트와 headers로 통신하는 방향으로 수정하였습니다.
- kakao_pk 값으로 프로젝트의 DB에 유저정보를 확인하여 없다면 create 있다면 get을 하였습니다.
- get후에 name, email의 변동여부를 if문으로 확인하고  변동이 있다면 수정하였습니다.
- 한번에 처리해도 query문이 한번일것 같아서 둘중 하나라도 변동이있다면 둘다 재적용하는 방식으로 하였습니다.
- 이방법의 경우 유저가 카카오계정을 탈퇴하고 동일한 정보로 가입한다면 버그가 발생하는데 다른방식으로 해야할까요?
- 아니면 카카오유저 컨트롤이 soft reset 방식이라면 통하는 방식일까요?!

2022-07-08 01:04 UTC, lordmyshepherd requested changes

2022-07-08 01:04 UTC, lordmyshepherd commented on users/tests.py
> +            status_code = 200
테스트 코드에 실제 개인정보로 작성이 되어 있는 것 같네요?
가짜 데이터로 수정만 해주시면 될 것 같습니다-!

2022-07-08 01:31 UTC, dingwan0331 commented on users/tests.py
> +            status_code = 200
수정 완료 하였습니다

2022-07-08 03:24 UTC, lordmyshepherd requested changes

2022-07-08 03:24 UTC, lordmyshepherd commented on users/views.py
> +                    user.save()
아래 코드로 수정하면 더 가독성이 좋아질 것 같은데 어떠신가요?
```suggestion
            user, created = User.objects.get_or_create(kakao_pk=kakao_pk, default = {"email" : email, "name" : nickname})
            
            if not created and not(user.email == email and user.name == nickname):
                user.email, user.name = email, nickname
                user.save()
```

2022-07-08 04:10 UTC, dingwan0331 commented on users/views.py
> +                    user.save()
너무 좋은것 같습니다!

2022-07-08 05:29 UTC, lordmyshepherd commented
LGTM 👍🏻

2022-07-08 05:30 UTC, lordmyshepherd approved these changes

2022-07-08 05:30 UTC, merged