[정진관]Create : ProductView & urls.py
wecode-bootcamp-korea/34-2nd-Fake-Trip-backend pull request #6
Opened 2022-07-06 17:50 UTC by dingwan0331

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ x ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 상품상세정보에 해당하는 Product View를 작성하였습니다.

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. product_id 를 path params로 활용하였습니다.
2. annotate와 집계함수를 사용하여 적용했습니다.
- price : 해당 숙박업소의 가장싼 방
- rating : 해당 숙박업소의 후기 별점 평균
- rating_count : 현재 숙박업소에 후기의 갯수
3. ProductImage 의 is_main 필드를 이용하여 대표이미지 여부를 True & False로 반환하였습니다.
4.prefetch related를 N+1 문제에 적용했습니다.
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
<br />

## :: 기타 질문 및 특이 사항
- 제품 상세페이지에 숙박업소의 모든룸의 예약이 꽉 찼을때 예약불가 메세지 기능이있습니다.
-  이 예약이 꽉찬 기준은 ProductList 에서 검색할때 설정한 날짜를 기준으로 예약불가여부를 판단하는데 이경우 QueryParams를 사용해야하나요??
- ex) ProductList에서 7월 23일 제주도를 검색하여서 제주도의 특정 호텔의 Product페이지로 넘어간다면 7월 23일에 예약이 가능한지 불가능한지 여부를 상세페이지에서 보여줍니다.

2022-07-07 02:12 UTC, lordmyshepherd requested changes

2022-07-07 02:12 UTC, lordmyshepherd commented on products/views.py
> +            'is_sold_out' : '공부 더 해야 가능할 것 같습니다....'
> 이 예약이 꽉찬 기준은 ProductList 에서 검색할때 설정한 날짜를 기준으로 예약불가여부를 판단하는데 이경우 QueryParams를 사용해야하나요??
이 질문은 GET을 사용해서 상품정보를 받아오기 때문에, query string 사용해서 받아오면 될 것 같습니다.

> ex) ProductList에서 7월 23일 제주도를 검색하여서 제주도의 특정 호텔의 Product페이지로 넘어간다면 7월 23일에 예약이 가능한지 불가능한지 여부를 상세페이지에서 보여줍니다.

불가능 여부가 상품에 표시되는건지  아니면 상품이 가지고 있는 각 룸에 표시되는건지 궁굼합니다!

2022-07-07 03:46 UTC, dingwan0331 commented on products/views.py
> +            'is_sold_out' : '공부 더 해야 가능할 것 같습니다....'
둘다 표시됩니다!
예약이 불가능한 룸은 해당 상품의 RoomList에 보이지 않고 예약이 가능한 룸만 보입니다.
Product에서는 해당 날짜에 가능한 룸이 하나도 없으면 상품에 예약불가 형태로 보입니다.

2022-07-08 09:01 UTC, dingwan0331 commented
** 테스트 코드 없습니다!! **
Query params 로 유저가 검색한 날짜를 기준으로 가격이 변동됩니다. 1박2일 2박3일  3박4일 검색마다 다르게 가격이 다릅니다.
예약 테이블과 비교하여 재고마감을 True False로 반환합니다.

2022-07-08 09:01 UTC, lordmyshepherd commented
> ** 테스트 코드 없습니다!! **
> Query params 로 유저가 검색한 날짜를 기준으로 가격이 변동됩니다. 1박2일 2박3일 3박4일 검색마다 다르게 가격이 다릅니다.
> 예약 테이블과 비교하여 재고마감을 True False로 반환합니다.

확인했습니다-! 리마인드 감사합니다!

2022-07-08 09:07 UTC, lordmyshepherd commented
LGTM 👍🏻

2022-07-09 00:56 UTC, merged