Create : ProductMainView & ProductSearchView & url.py
wecode-bootcamp-korea/34-2nd-Fake-Trip-backend pull request #8
Opened 2022-07-07 05:57 UTC by miracle-21

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 메인페이지, 검색결과페이지에서 숙소 리스트 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 메인페이지 데이터
- 지역, 성급, 체크인 시간대 별로 숙소 리스트를 한 번에 10개 까지 불러올 수 있다.
- 랜덤 sort 가능
- 체크인 시간을 오름차순으로 sort 가능
- response : 숙소 id, 종류,지역, 이름, 메인 사진, 가격, 체크인 시간 반환. 별점은 아직 데이터가 없어서 보류. 
2. 검색결과페이지 데이터
- 지역, 숙소 이름 별로 숙소 리스트를 한 번에 10개 까지 불러올 수 있다. 날짜별, 인원별 리스트는 아직 데이터가 없어서 보류.
- 랜덤 sort 가능
- response : 숙소 id, 이름, 성급, 주소, 메인 사진 반환. 

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 역참조 데이터 불러오기.
- aggregate, 집계함수 사용.

<br />

## :: 기타 질문 및 특이 사항

2022-07-07 06:52 UTC, lordmyshepherd requested changes

2022-07-07 06:52 UTC, lordmyshepherd commented on products/views.py
> +        check_in = request.GET.get('check_in', None)
예약 날짜에 필요한 check_in 날짜만 받아도 되는 건가요? 
check_out은 필요 없을까요?

2022-07-07 06:52 UTC, lordmyshepherd commented on products/views.py
> +            'check_in-ascending' : 'check_in',
`'check_in-ascending'` 이 부분은 정상적으로 필터링이 되는지 확인이 필요할 것 같습니다!
제대로 필터링 되나요?

2022-07-07 06:52 UTC, lordmyshepherd commented on products/views.py
> +        print(q)
프린트문은 지워주세요-!

2022-07-07 06:52 UTC, lordmyshepherd commented on products/views.py
> +                #'rating' : [review.rating for review in product.reviews.all()]
마찬가지로 주석도 지워주세요-!
코드를 push하신 후에 최종적으로 PR에 file change 버튼을 눌러서 확인해주셔야 합니다-!

2022-07-07 06:52 UTC, lordmyshepherd commented on products/views.py
> +        check_in = request.GET.get('check_in', None)
![스크린샷 2022-07-07 오후 3 50 02](https://user-images.githubusercontent.com/53214510/177709912-0e36a542-17da-4330-865a-70b654024372.png)

2022-07-07 06:52 UTC, lordmyshepherd commented on products/views.py
> +class ProductSearchView(View):
`ProductSearchView`와 `ProductMainView`는 동일하게 상품 목록을 반환하는 엔드포인트입니다.
서로 코드가 많이 중복되는 것 같습니다.

이 두 가지 View를 하나로 합칠 수 있는 방법을 고민해보시고 리펙토링 해보시면 좋을 것 같습니다!

2022-07-07 06:52 UTC, lordmyshepherd commented on products/views.py
> +class ProductMainView(View):
👍🏻  전반적으로 코드 잘 작성해 주셨습니다-!

2022-07-08 05:22 UTC, miracle-21 commented on products/views.py
> +        check_in = request.GET.get('check_in', None)
> check_in, check_out 날짜는 reservations 날짜와 달라서 숙박 기간과는 상관 없지만, 조건 검색 시 필요할 수도 있어서 추가하겠습니다.

2022-07-08 05:52 UTC, miracle-21 commented on products/views.py
> +            'check_in-ascending' : 'check_in',
test code 추가하겠습니다.

2022-07-08 05:53 UTC, miracle-21 commented on products/views.py
> +        print(q)
넵

2022-07-08 05:54 UTC, miracle-21 commented on products/views.py
> +                #'rating' : [review.rating for review in product.reviews.all()]
넵

2022-07-08 05:54 UTC, miracle-21 commented on products/views.py
> +class ProductSearchView(View):
넵

2022-07-08 06:30 UTC, lordmyshepherd commented on products/views.py
> +        check_in = request.GET.get('check_in', None)
민하님 제가 궁굼한 것은 검색에서 사용하는 check_in, check_out이 reservations 날짜를 기준으로 필터링 되야되는 것이 아닌가요?

2022-07-08 06:35 UTC, miracle-21 commented on products/views.py
> +        check_in = request.GET.get('check_in', None)
product 기준으로 check_in, check_out이 정해져서 reservation 날짜를 기준으로 검색하는 검색기능에서는 상관이 없습니다. check_in, check_out 은 검색 목적으로 만든게 아니라 메인페이지에 테마별로 숙소 리스트를 나열 할 때 사용하려고 만들었습니다!

2022-07-08 07:14 UTC, lordmyshepherd commented on products/views.py
> +        check_in = request.GET.get('check_in', None)
메인 페이지의 테마별로 나열하는 목적이라고 하셨는데, 코드는 숙소의 체크인을 기준으로 필터링하고 있습니다!

<img width="757" alt="스크린샷 2022-07-08 오후 4 13 21" src="https://user-images.githubusercontent.com/53214510/177937709-ba8e890f-d1a3-454d-9a14-dc95996e7374.png">

```python
        if check_in:
            q &= Q(check_in = check_in)

        if check_out:
            q &= Q(check_in__gte = check_out)
```

실제로

2022-07-08 07:26 UTC, miracle-21 commented on products/views.py
> +        check_in = request.GET.get('check_in', None)
'제주도 5성급 호텔', '가성비 호텔', '체크인 빠른 호텔' 이런식으로 메인 페이지에 숙소 리스트를 만들기 위해 추가한 기능입니다.

2022-07-08 07:33 UTC, lordmyshepherd commented on products/views.py
> +        check_in = request.GET.get('check_in', None)
체크인 빠른 호텔이군요! 그런데 체크인 빠른 호텔이면 check_in을 필터가 아니라 order_by를 사용해서 정렬해줘야할 것 같습니다!

2022-07-08 08:12 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-07-08 08:12 UTC, merged